### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by andymans** [dao-xyz/peerbit#56]
It's crazy to me that a product with as much potential as this one only has 49 stars. But there's a reason: you have no docs. People don't have time to wade through the source to find out how to get stuff done.

I think it's worth figuring out what features people would like this product for. And then documenting "how to" get those features into their app. Your stars will go to 4.9 K almost overnight! In any case -great effort so far & good luck!

**Comment by marcus-pousette** [comment]
Thanks for reaching out! 

> It's crazy to me that a product with as much potential as this one only has 49 stars. But there's a reason: you have no docs. People don't have time to wade through the source to find out how to get basic suff done:

Yes, it is definitely a problem that there is not currently good documentation. That has not been prioritised yet.  Currently we are working towards a P2P streaming and media platform. Peerbit is kind of a consequence of this and we are working backwards from this end-use case. Crazy low latency and high throughput is needed because we are going to do conference calls with high resolution video as an example. So developing resources are right now put into simplifying the infrastructure layer to create an autodialer that conditioned on the what data needs to be sent quickly and not. Due to that this might lead to some API  changes and that resources limited, documentation has been pushed into the future. 

It is going to be pretty exciting once this work is finalised since it will greatly improve the DX.
 
> When a change is detected, query the db and then iterate over all the records, reading each one. (surprisingly I cannot loop over one of your "Results" objects to correctly achieve this this and I have > 30 years experience as a coder!)
 
Right now the [boilerplate project](https://github.com/dao-xyz/peerbit-getting-started) and the tests it contains is the best starting point. Together with the [examples](https://github.com/dao-xyz/peerbit-examples).  For this particular problem, the Result API is kind of tricky, it is double loop, where the outer loop corresponds to one peer, and in the inner corresponds to the results from that peer. 

Generally the index.query response should be trivial to use and it is not at the moment. I created a new issue for this specifically #57 

> I think it's worth figuring out what features people would like this product for. And then documenting "how to" achieve those features. Your stars will go to 4.9 K almost overnight!

Thats a great idea, thanks! If you have an use-cases in mind, or any small project you would like to see how they would look like with Peerbit as backend, please let me know.

**Comment by andymans** [comment]
Ah - yes I discovered about the double-loop...in the results api...mainly by trial and error! But no matter - I have it working. 
In terms of Use Cases - I think Collaborative Apps may be the sweet spot. These can be anything from small to fairly large. As a matter of interest I looked at https://github.com/microsoft/FluidFramework. It's a nice framework - but it's HUGE, and relies on massive Kafka clusters and multiple other heavyweight (and centralised) components to achieve what Peerbit  can do out of the box. I'll think more on this question..

**Comment by andymans** [comment]
Marking as closed.

**Comment by marcus-pousette** [comment]
> Ah - yes I discovered about the double-loop...in the results api...mainly by trial and error! But no matter - I have it working. 

Great!

> In terms of Use Cases - I think Collaborative Apps may be the sweet spot. These can be anything from small to fairly large. As a matter of interest I looked at https://github.com/microsoft/FluidFramework. It's a nice framework - but it's HUGE, and relies on massive Kafka clusters and multiple other heavyweight (and centralised) components to achieve what Peerbit can do out of the box. I'll think more on this question..

Yes. There is a lot of things you can dive into there. In its essence P2P technology (if done right) can fundamentally decrease the complexity of an tech stack since there are much less "moving" parts. This is especially true for collaboration like apps.
Thanks!

**Comment by marcus-pousette** [comment]
@andymans  an update, there has been some major work done in improving the documentation and examples past month.

- [peerbit.org](peerbit.org) a dedicated website for docs
- Major work has been done to simplify the API of various components of Peerbit, especially the document store.
- Example repo has been reworked and improved  https://github.com/dao-xyz/peerbit-examples
